/*
 * This source file was generated by the Gradle 'init' task
 */
// IRCTC App
// 1. Gather Functional Requirements
// 1. a. User Registration and Login
// 1. b. Train Search and Booking
// 1. c. Show available seats
// 2. Prepare low level design
// 3. Identify Main Entities and their Attributes
// 3. a. User Entity: userID, name, hashedPassword, ticketsBooked
// 3. b. Ticket Entity: String Ticket, String user, String source, String destination, Datetime, Train train
// 3. c. Train Entity: trainID, trainNumber, departureTime, arrivalTime, List<List<Boolean>> availableSeats
// 4. Creating services - services are classes that contain business logic and uses the entities to perform operations.
// 4. Service - UserBookingService, TrainService
// 4. a. Methods: registerUser(), loginUser(), fetchBookings(), cancelBooking(), bookTicket()
// 4. b. Methods: searchTrains(), getAvailableSeats(), updateSeatAvailability()
// 5. Define Relationships between Entities
// Gradle - build automation tool used for dependency management and project build
//package declaration 
//it is important to match the directory structure
// for proper organization and accessibility of the code.
// In this case, the file is located in 'org/example/app' directory.
// Thus, the package declaration is as follows:
// Whenever you create a new Java file, ensure that the package declaration
// at the top of the file corresponds to its directory structure.
package org.example.app;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.Scanner;
import java.util.UUID;
import java.util.stream.Collectors;

import org.example.app.Util.UserServiceUtil;
import org.example.app.entities.Train;
import org.example.app.entities.User;
import org.example.app.services.UserBookingService;

public class App {

    public static void main(String[] args) throws IOException {
        // We have made a separate Test method to keep the main method clean and readable.
        // this is static method, so we can directly call it using class name without creating object of this class.
        // Test();
        System.out.println("Running Train Booking System...");
        try (Scanner scanner = new Scanner(System.in)) {
            int option = 0;
            // Defining UserBookingService variable here to use it inside try block. We have not initialized it yet.
            UserBookingService userBookingService;
            try {
                // Using default constructor to load all users.
                // userBookingService = new UserBookingService() means we are calling the default constructor of UserBookingService class.
                userBookingService = new UserBookingService();
            } catch (IOException e) {
                e.printStackTrace();              // <‑‑ add this
                System.out.println("There is something wrong");
                return;
            }
            while (option != 7) {
                System.out.println("1. SignUp User");
                System.out.println("2. Login User");
                System.out.println("3. Fetch Bookings");
                System.out.println("4. Search Trains");
                System.out.println("5. Book a Seat");
                System.out.println("6. Cancel my Booking");
                System.out.println("7. Exit the App");
                System.out.print("Enter your option: ");
                option = scanner.nextInt();
                Train trainSelectedForBooking = new Train();
                switch (option) {
                    case 1 -> {
                        // Call Signup user method
                        System.out.println(" Enter the username to signup");
                        String nameToSignup = scanner.next();
                        System.out.println(" Enter the password to signup");
                        String passwordToSignup = scanner.next();
                        User userToSignup = new User(nameToSignup, passwordToSignup, UserServiceUtil.hashPassword(passwordToSignup), new ArrayList<>(), UUID.randomUUID().toString());
                        userBookingService.signUp(userToSignup);
                    }
                    case 2 -> {
                        // Call login user method
                        // Here we are taking username and password input from user to login.
                        // And creating a user object with that username and password.
                        // And then passing that user object to the constructor of UserBookingService class to initialize the user field of that class.
                        // Then we are calling the loginUser method of UserBookingService class to check if the user exists in the user list.
                        System.out.println(" Enter the username to login");
                        String nameToLogin = scanner.next();
                        System.out.println(" Enter the password to login");
                        String passwordToLogin = scanner.next();
                        User userToLogin = new User(nameToLogin, passwordToLogin, UserServiceUtil.hashPassword(passwordToLogin), new ArrayList<>(), UUID.randomUUID().toString());
                        try {
                            userBookingService = new UserBookingService(userToLogin);
                            Boolean loginSuccess = userBookingService.loginUser();
                            if (loginSuccess) {
                                System.out.println("Login Successful");
                            } else {
                                System.out.println("Login Failed");
                            }
                        } catch (IOException e) {
                            System.out.println("There is something wrong");
                            return;
                        }
                    }
                    case 3 -> {
                        // Call fetch bookings method
                        System.out.println("Fetching your bookings...");
                        userBookingService.fetchBookings();
                    }
                    case 4 -> {
                        // Call book ticket method
                        System.out.println("Type your source station");
                        String source = scanner.next();
                        System.out.println("Type your destination station");
                        String destination = scanner.next();
                        List<Train> trains = userBookingService.getTrains(source, destination);
                        int index = 1;
                        for (Train t : trains) {
                            System.out.println(index + "Train id: " + t.getTrainId());
                            for (Map.Entry<String, String> entry : t.getStationTimes().entrySet()) {
                                System.out.println("Station: " + entry.getKey() + "time: " + entry.getValue());
                            }
                            index++;
                        }
                        System.out.println("Select a train to book by typing 1,2,3...");
                        try {
                            trainSelectedForBooking = trains.get(scanner.nextInt());
                        } catch (Exception e) {
                            // TODO Auto-generated catch block
                            e.printStackTrace();
                        }
                    }
                    case 5 -> {
                        //Seat booking method
                        System.out.println("Select a seat to book");
                        List<List<Integer>> seats = userBookingService.fetchSeats(trainSelectedForBooking);
                        for (List<Integer> seatRow : seats) {
                            for (Integer seat : seatRow) {
                                System.out.print(seat + " ");
                            }
                            System.out.println();
                        }
                        System.out.println("Select the seat by typing row and column number");
                        System.out.println("Row number:");
                        int row = scanner.nextInt();
                        System.out.println("Column number:");
                        int column = scanner.nextInt();
                        System.out.println("Booking your seat...");
                        Boolean booked = userBookingService.bookTrainSeat(trainSelectedForBooking, row, column);
                        if (booked) {
                            System.out.println("Seat booked successfully");
                        } else {
                            System.out.println("Seat booking failed");
                        }
                    }
                    case 6 -> {
                    }
                    case 7 ->
                        System.out.println("Exiting...");
                    default ->
                        System.out.println("Invalid option. Please try again.");
                }
                // We are taking input from user to perform different operations.
                //
                // Call cancel booking method
            }
        }
    }

    public static void Test() {
        //Arrays.asList creates a fixed-size list backed by the specified array.
        List<Integer> l = Arrays.asList(1, 2, 3, 4, 5);
        //stream() method is used to convert the list into a stream.
        //filter() method is used to filter the elements of the stream based on a given predicate.
        //predicate here is i -> i%2 == 0 which checks if the number is even. It is a lambda expression. It is a functional interface. In Java 8, functional interfaces can be implemented using lambda expressions. They are first class citizens in Java 8 which means we can pass them as parameters to methods, return them from methods, and assign them to variables.
        //lambda expression is a short block of code which takes in parameters and returns a value.
        //collect() method is used to collect the filtered elements back into a list.
        //Collectors.toList() is a static method from the Collectors class that provides a collector
        //which accumulates the input elements into a new List.
        List<Integer> l1 = l.stream().filter(i -> i % 2 == 0).collect(Collectors.toList());
    }
}
